package model;
// Generated May 2, 2012 9:47:21 AM by Hibernate Tools 3.2.1.GA



/**
 * Buku generated by hbm2java
 */
public class Buku  implements java.io.Serializable {


     private Integer id_post;
     private String username;
     private String title;
     private String content;
     private String date;

    public Buku() {
    }

    public Buku(Integer id_post, String username, String title, String content, String date) {
        this.id_post = id_post;
        this.username = username;
        this.title = title;
        this.content = content;
        this.date = date;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getId_post() {
        return id_post;
    }

    public void setId_post(Integer id_post) {
        this.id_post = id_post;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    




}


