package model;
// Generated Jun 20, 2012 11:34:37 AM by Hibernate Tools 3.2.1.GA



/**
 * Posts generated by hbm2java
 */
public class Posts implements java.io.Serializable {


     private Integer id_post;
     private String username;
     private String title;
     private String content;
     private String date;

    public Posts() {
    }

    public Posts(Integer id_post, String username, String title, String content, String date) {
       this.id_post = id_post;
       this.username = username;
       this.title = title;
       this.content = content;
       this.date = date;
    }

    public Integer getId_post() {
        return id_post;
    }
    
    public void setId_post(Integer id_post) {
        this.id_post = id_post;
    }
   
    
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


